[project]
name = "Koko"
version = "0.0.0"
description = "Self-hosted media server."
repository = "https://github.com/LizardByte/Koko"
logo = "assets/Koko.svg"
favicon = "assets/Koko.svg"

[build]
output = "_site"
work = ".dockle"
strict = true
clean = true

[[targets]]
name = "api"
title = "Koko Rust API"
framework = "rustdoc"
source = "."
home = true
