# Sonar project analysis properties overrides
# Automatic analysis ignores this file, and uses .sonarcloud.properties instead

sonar.projectKey=LizardByte_Koko

sonar.exclusions=third-party/**, packaging/linux/flatpak/deps/**
