ALTER TABLE scan_state ADD COLUMN scan_revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE scan_state ADD COLUMN last_scanned_at BIGINT DEFAULT NULL;

ALTER TABLE media_files ADD COLUMN display_title TEXT DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN container TEXT DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN duration_ms BIGINT DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN bit_rate BIGINT DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN width INTEGER DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN height INTEGER DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN video_codec TEXT DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN audio_codec TEXT DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN metadata_json TEXT DEFAULT NULL;
ALTER TABLE media_files ADD COLUMN metadata_updated_at BIGINT DEFAULT NULL;

