---
name: CI

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup_release:
    name: Setup Release
    outputs:
      publish_release: ${{ steps.setup_release.outputs.publish_release }}
      release_body: ${{ steps.setup_release.outputs.release_body }}
      release_commit: ${{ steps.setup_release.outputs.release_commit }}
      release_generate_release_notes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
      release_tag: ${{ steps.setup_release.outputs.release_tag }}
      release_version: ${{ steps.setup_release.outputs.release_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release
        id: setup_release
        uses: LizardByte/setup-release-action@v2025.102.14715
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    # TODO: setup strategy matrix and/or cross compile
    name: Build
    needs: setup_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/work/_temp/_github_home/.cargo/registry
            ~/work/_temp/_github_home/.cargo/git
            target
          key: ${{ github.job }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ hashFiles('rust-toolchain.toml') }}-

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libayatana-appindicator3-dev \
            libglib2.0-dev \
            libgtk-3-dev \
            libxdo-dev

      - name: Install dependencies
        run: |
          # cargo-bin --install doesn't work without a lock file
          # https://github.com/dustinblackman/cargo-run-bin/issues/27
          # cargo install cargo-run-bin
          # cargo-bin --install

          cargo install cargo-edit
          cargo install cargo-tarpaulin

      - name: Update Version
        if: ${{ needs.setup_release.outputs.publish_release == 'true' }}
        run: cargo set-version ${{ needs.setup_release.outputs.release_version }}

      - name: Test
        id: test
        run: |
          cargo tarpaulin \
            --engine llvm \
            --out Xml

      - name: Upload coverage
        # any except canceled or skipped
        if: >-
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@v5
        with:
          disable_search: true
          fail_ci_if_error: true
          files: cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Install toolchain
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build --target x86_64-unknown-linux-gnu --release

      - name: Strip all debug symbols
        run: strip --strip-all target/x86_64-unknown-linux-gnu/release/koko

      - name: Enable reading of cache
        # TODO: is this necessary
        continue-on-error: true
        run: chmod -R a+rwX $HOME/.cargo target

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: koko-x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/koko

      - name: Create/Update GitHub Release
        if: false
        # if: ${{ needs.setup_release.outputs.publish_release == 'true' }}
        uses: LizardByte/create-release-action@v2025.102.13208
        with:
          allowUpdates: true
          artifacts: 'target/x86_64-unknown-linux-gnu/release/koko'
          body: ${{ needs.setup_release.outputs.release_body }}
          generateReleaseNotes: ${{ needs.setup_release.outputs.release_generate_release_notes }}
          name: ${{ needs.setup_release.outputs.release_tag }}
          prerelease: true
          tag: ${{ needs.setup_release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}
